# NumPy Fundamentals - Practice & Exercise Notebook 🏋️‍♂️

Welcome to the hands-on practice notebook for **Lecture 5: NumPy Fundamentals**!

### Instructions:
1. Complete each exercise by writing your solution code in the code cells marked `# YOUR CODE HERE`.
2. Run the provided **Verification / Test** cells below each exercise to check if your answer is correct.
3. Try to solve the exercises without looking at the solution notebook first!
4. Have fun learning NumPy!

---


## Setup: Import NumPy

In [2]:
# Import numpy library using standard alias
import numpy as np

print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.0.1


## Exercise 1: Array Creation Warm-up 🧱

**Task:**
1. Create a 1D array named `arr_seq` containing integers from `10` to `50` (inclusive) with a step of `5` (i.e. `10, 15, 20, ..., 50`).
2. Create a `4x4` identity matrix named `arr_identity`.
3. Create a 1D array named `arr_space` with `5` evenly spaced values between `0` and `1`.

> **Hint:** Use `np.arange()`, `np.eye()`, and `np.linspace()`.


In [3]:
# YOUR CODE HERE
arr_seq = np.arange (10, 51, 5)
arr_identity = np.eye(4,4)
arr_space = np.linspace(0, 1, 5)

# Print your results
print("arr_seq:", arr_seq)
print("arr_identity:\n", arr_identity)
print("arr_space:", arr_space)


arr_seq: [10 15 20 25 30 35 40 45 50]
arr_identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arr_space: [0.   0.25 0.5  0.75 1.  ]


In [4]:
# VERIFICATION TEST 1
assert arr_seq is not None, "arr_seq is None"
assert arr_identity is not None, "arr_identity is None"
assert arr_space is not None, "arr_space is None"

np.testing.assert_array_equal(arr_seq, np.array([10, 15, 20, 25, 30, 35, 40, 45, 50]))
np.testing.assert_array_equal(arr_identity, np.eye(4))
np.testing.assert_allclose(arr_space, np.array([0.0, 0.25, 0.5, 0.75, 1.0]))

print("✅ Exercise 1 Passed!")


✅ Exercise 1 Passed!


## Exercise 2: Inspecting Array Properties 🔍

**Task:**
Given the 3D array `matrix_3d` below:
1. Store its number of dimensions in `num_dim`.
2. Store its shape in `arr_shape`.
3. Store its total number of elements in `arr_size`.
4. Store its data type in `arr_dtype`.

> **Hint:** Use attributes `.ndim`, `.shape`, `.size`, and `.dtype`.


In [5]:
matrix_3d = np.ones((2, 3, 4), dtype=np.float32)

# YOUR CODE HERE
num_dim = matrix_3d.ndim
arr_shape = matrix_3d.shape
arr_size = matrix_3d.size
arr_dtype = matrix_3d.dtype

print(f"Dimensions: {num_dim}, Shape: {arr_shape}, Size: {arr_size}, Dtype: {arr_dtype}")


Dimensions: 3, Shape: (2, 3, 4), Size: 24, Dtype: float32


In [6]:
# VERIFICATION TEST 2
assert num_dim == 3, f"Expected 3 dimensions, got {num_dim}"
assert arr_shape == (2, 3, 4), f"Expected shape (2, 3, 4), got {arr_shape}"
assert arr_size == 24, f"Expected size 24, got {arr_size}"
assert arr_dtype == np.float32, f"Expected float32, got {arr_dtype}"

print("✅ Exercise 2 Passed!")


✅ Exercise 2 Passed!


## Exercise 3: Vectorized Operations ⚡

**Task:**
You are given a list of temperatures in Celsius: `[0, 15, 22.5, 30, 37, 100]`.
1. Convert this list into a NumPy array `celsius`.
2. Convert all values to Fahrenheit using the formula: $F = C \times 1.8 + 32$. Store the result in `fahrenheit`. Do **NOT** use any Python loops (`for` / `while`).

> **Hint:** Vectorization allows performing arithmetic directly on NumPy arrays!


In [7]:
# YOUR CODE HERE
list1 = [0, 15, 22.5, 30, 37, 100]
celsius = np.array(list1)
fahrenheit = (celsius * 1.8) + 32

print("Celsius:", celsius)
print("Fahrenheit:", fahrenheit)


Celsius: [  0.   15.   22.5  30.   37.  100. ]
Fahrenheit: [ 32.   59.   72.5  86.   98.6 212. ]


In [8]:
# VERIFICATION TEST 3
expected_f = np.array([32.0, 59.0, 72.5, 86.0, 98.6, 212.0])
np.testing.assert_allclose(fahrenheit, expected_f)

print("✅ Exercise 3 Passed!")


✅ Exercise 3 Passed!


## Exercise 4: Matrix Operations & Transposition 📐

**Task:**
Given matrix $A$ (shape 2x3) and matrix $B$ (shape 3x2):
1. Compute the matrix product $C = A \cdot B$ (result shape 2x2) using the matrix multiplication operator `@` or `np.dot()`.
2. Transpose matrix $C$ to get $C^T$ and store it in `C_transposed`.

> **Hint:** `@` or `np.dot()` performs matrix multiplication. Use `.T` or `np.transpose()` for transpose.


In [9]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

B = np.array([[7, 8], 
              [9, 10], 
              [11, 12]])

# YOUR CODE HERE
C = np.dot(A, B)
C_transposed = np.transpose(C)

print("Matrix C (A @ B):\n", C)
print("C Transposed:\n", C_transposed)


Matrix C (A @ B):
 [[ 58  64]
 [139 154]]
C Transposed:
 [[ 58 139]
 [ 64 154]]


In [10]:
# VERIFICATION TEST 4
expected_C = np.array([[58, 64], [139, 154]])
expected_C_T = np.array([[58, 139], [64, 154]])

np.testing.assert_array_equal(C, expected_C)
np.testing.assert_array_equal(C_transposed, expected_C_T)

print("✅ Exercise 4 Passed!")


✅ Exercise 4 Passed!


## Exercise 5: Boolean Masking & Grade Curving 🎯

**Task:**
Given an array of student exam scores `scores = np.array([45, 88, 52, 95, 38, 71, 60, 49, 82])`:
1. Create a boolean mask `passed_mask` for scores $\ge 50$.
2. Extract all passing scores into an array `passing_scores`.
3. Count how many students passed and store the count in `num_passed`.
4. Curve the grades: Create a new array `curved_scores` where all failing scores (< 50) are replaced with `50`, while passing scores remain unchanged.

> **Hint:** Use boolean comparison operators and `np.where(condition, x, y)`.


In [14]:
scores = np.array([45, 88, 52, 95, 38, 71, 60, 49, 82])

# YOUR CODE HERE
passed_mask = scores>=50
passing_scores = scores[scores>=50]
num_passed = sum(passed_mask)
curved_scores = np.where(scores<50, 50, scores)
print(passed_mask)
print("Passing scores:", passing_scores)
print("Number of students passed:", num_passed)
print("Curved scores:", curved_scores)


[False  True  True  True False  True  True False  True]
Passing scores: [88 52 95 71 60 82]
Number of students passed: 6
Curved scores: [50 88 52 95 50 71 60 50 82]


In [15]:
# VERIFICATION TEST 5
np.testing.assert_array_equal(passing_scores, np.array([88, 52, 95, 71, 60, 82]))
assert num_passed == 6, f"Expected 6, got {num_passed}"
np.testing.assert_array_equal(curved_scores, np.array([50, 88, 52, 95, 50, 71, 60, 50, 82]))

print("✅ Exercise 5 Passed!")


✅ Exercise 5 Passed!


## Exercise 6: Reshaping and Stacking Arrays 🧩

**Task:**
1. Start with a 1D array `arr_12` containing numbers from `0` to `11`.
2. Reshape `arr_12` into a `3x4` matrix named `mat_3x4`.
3. Create a `3x2` matrix of ones named `ones_3x2`.
4. Horizontally stack `mat_3x4` and `ones_3x2` into a `3x6` matrix named `stacked_mat`.
5. Flatten `stacked_mat` into a 1D array named `flat_arr`.

> **Hint:** Use `.reshape()`, `np.hstack()`, and `.flatten()`.


In [18]:
# YOUR CODE HERE
arr_12 = np.arange(12)
mat_3x4 = arr_12.reshape(3,4)
ones_3x2 = np.ones((3, 2), dtype=int)
stacked_mat = np.hstack([mat_3x4, ones_3x2])
flat_arr = stacked_mat.flatten()

print("Stacked Matrix (3x6):\n", stacked_mat)
print("Flat Array shape:", flat_arr.shape if flat_arr is not None else None)


Stacked Matrix (3x6):
 [[ 0  1  2  3  1  1]
 [ 4  5  6  7  1  1]
 [ 8  9 10 11  1  1]]
Flat Array shape: (18,)


In [19]:
# VERIFICATION TEST 6
assert mat_3x4.shape == (3, 4), f"Expected (3, 4), got {mat_3x4.shape}"
assert stacked_mat.shape == (3, 6), f"Expected (3, 6), got {stacked_mat.shape}"
assert flat_arr.shape == (18,), f"Expected (18,), got {flat_arr.shape}"

expected_stacked = np.array([
    [0, 1, 2, 3, 1, 1],
    [4, 5, 6, 7, 1, 1],
    [8, 9, 10, 11, 1, 1]
])
np.testing.assert_array_equal(stacked_mat, expected_stacked)

print("✅ Exercise 6 Passed!")


✅ Exercise 6 Passed!


## Exercise 7: Axis Statistics 📊

**Task:**
Below is a matrix of exam scores for `4` students across `3` subjects:
```python
exam_data = np.array([
    [85, 90, 78],  # Student 0
    [60, 75, 80],  # Student 1
    [92, 88, 95],  # Student 2
    [70, 65, 72]   # Student 3
])
```
1. Calculate the mean score for **each student** (across subjects) and store in `student_means` (shape: `(4,)`).
2. Calculate the highest score for **each subject** (across students) and store in `subject_maxes` (shape: `(3,)`).
3. Find the overall maximum score in the entire matrix `overall_max` and the index of the highest scoring student (row index) `best_student_idx`.

> **Hint:** Remember `axis=1` operates across columns (for each row), and `axis=0` operates across rows (for each column).


In [25]:
exam_data = np.array([
    [85, 90, 78],
    [60, 75, 80],
    [92, 88, 95],
    [70, 65, 72]
])

# YOUR CODE HERE
student_means = np.mean(exam_data, axis=1)
subject_maxes = np.max(exam_data, axis=0)
overall_max = np.max(exam_data)
best_student_idx = np.argmax(student_means)

print("Student Means:", student_means)
print("Subject Maxes:", subject_maxes)
print("Overall Max:", overall_max)
print("Best Student Index:", best_student_idx)


Student Means: [84.33333333 71.66666667 91.66666667 69.        ]
Subject Maxes: [92 90 95]
Overall Max: 95
Best Student Index: 2


In [26]:
# VERIFICATION TEST 7
np.testing.assert_allclose(student_means, np.array([84.333333, 71.666667, 91.666667, 69.0]), rtol=1e-5)
np.testing.assert_array_equal(subject_maxes, np.array([92, 90, 95]))
assert overall_max == 95, f"Expected 95, got {overall_max}"
assert best_student_idx == 2, f"Expected student index 2, got {best_student_idx}"

print("✅ Exercise 7 Passed!")


✅ Exercise 7 Passed!


## Exercise 8: Data Standardization via Broadcasting 📡

**Task:**
Standardization (Z-score normalization) transforms dataset features to have `mean = 0` and `std = 1` using the formula:
$$Z = \frac{X - \mu}{\sigma}$$
where $\mu$ is the mean of each column and $\sigma$ is the standard deviation of each column.

Given dataset `X` of shape `(4, 2)`:
1. Compute `col_means` (mean of each column).
2. Compute `col_stds` (std deviation of each column).
3. Compute standardized data `X_std` using NumPy broadcasting.

> **Hint:** NumPy automatically broadcasts shape `(2,)` vectors across `(4, 2)` matrices!


In [33]:
X = np.array([
    [10.0, 200.0],
    [20.0, 400.0],
    [30.0, 100.0],
    [40.0, 300.0]
])

# YOUR CODE HERE
col_means = np.mean(X, axis=0)
col_stds = np.std(X, axis=0)
X_std = (X-col_means)/col_stds

print("Column Means:", col_means)
print("Column Stds:", col_stds)
print("Standardized X:\n", X_std)


Column Means: [ 25. 250.]
Column Stds: [ 11.18033989 111.80339887]
Standardized X:
 [[-1.34164079 -0.4472136 ]
 [-0.4472136   1.34164079]
 [ 0.4472136  -1.34164079]
 [ 1.34164079  0.4472136 ]]


In [34]:
# VERIFICATION TEST 8
np.testing.assert_allclose(col_means, np.array([25.0, 250.0]))
np.testing.assert_allclose(col_stds, np.array([11.18033989, 111.80339887]))

# Standardized data should have mean ~ 0 and std ~ 1
np.testing.assert_allclose(np.mean(X_std, axis=0), np.array([0.0, 0.0]), atol=1e-7)
np.testing.assert_allclose(np.std(X_std, axis=0), np.array([1.0, 1.0]), atol=1e-7)

print("✅ Exercise 8 Passed!")


✅ Exercise 8 Passed!


## Exercise 9: Random Numbers & Sampling 🎲

**Task:**
1. Set the random seed to `42` using `np.random.seed(42)`.
2. Generate a `3x3` matrix `rand_matrix` of random numbers drawn from a **standard normal distribution** (mean=0, std=1).
3. Draw a random sample of `3` unique numbers without replacement from `np.arange(10, 100)` and store in `rand_sample`.

> **Hint:** Use `np.random.randn()` and `np.random.choice(..., replace=False)`.


In [35]:
# YOUR CODE HERE
np.random.seed(42)

rand_matrix = np.random.randn(3,3)
rand_sample = np.random.choice(np.arange(10,100), replace=False, size=3)

print("Random 3x3 Matrix:\n", rand_matrix)
print("Random Sample:", rand_sample)


Random 3x3 Matrix:
 [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
Random Sample: [90 14 50]


In [36]:
# VERIFICATION TEST 9
np.random.seed(42)
expected_mat = np.random.randn(3, 3)
expected_sample = np.random.choice(np.arange(10, 100), size=3, replace=False)

np.testing.assert_allclose(rand_matrix, expected_mat)
np.testing.assert_array_equal(rand_sample, expected_sample)

print("✅ Exercise 9 Passed!")


✅ Exercise 9 Passed!


## Exercise 10: Cleaning Missing Data (NaN) 🧹

**Task:**
You are given an array with missing entries: `data_nan = np.array([12.0, np.nan, 18.0, 24.0, np.nan, 30.0])`.
1. Calculate the mean of valid (non-NaN) entries and store in `valid_mean`.
2. Create a clean array `data_imputed` where all `NaN` values are replaced by `valid_mean`.

> **Hint:** Use `np.nanmean()` and `np.where(np.isnan(...), ...)` or `np.nan_to_num()`.


In [38]:
data_nan = np.array([12.0, np.nan, 18.0, 24.0, np.nan, 30.0])

# YOUR CODE HERE
valid_mean = np.nanmean(data_nan)
data_imputed = data_nan[~np.isnan(data_nan)]

print("Valid Mean:", valid_mean)
print("Imputed Data:", data_imputed)


Valid Mean: 21.0
Imputed Data: [12. 18. 24. 30.]


In [39]:
# VERIFICATION TEST 10
assert valid_mean == 21.0, f"Expected mean 21.0, got {valid_mean}"
assert not np.isnan(data_imputed).any(), "data_imputed still contains NaN values!"
np.testing.assert_allclose(data_imputed, np.array([12.0, 21.0, 18.0, 24.0, 21.0, 30.0]))

print("✅ Exercise 10 Passed!")


AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(shapes (4,), (6,) mismatch)
 ACTUAL: array([12., 18., 24., 30.])
 DESIRED: array([12., 21., 18., 24., 21., 30.])

## Exercise 11: Binary Array I/O 💾

**Task:**
1. Save the matrix `sample_arr = np.array([[10, 20], [30, 40]])` to a binary file named `test_matrix.npy`.
2. Load the binary file back into a variable `loaded_arr`.
3. Verify that `loaded_arr` matches `sample_arr`.

> **Hint:** Use `np.save()` and `np.load()`.


In [42]:
sample_arr = np.array([[10, 20], [30, 40]])

# YOUR CODE HERE
np.save("test_matrix.npy", sample_arr)

# 2. Load array
loaded_arr = np.load("test_matrix.npy")

print("Loaded Array:\n", loaded_arr)


Loaded Array:
 [[10 20]
 [30 40]]


In [43]:
# VERIFICATION TEST 11
import os
assert os.path.exists("test_matrix.npy"), "File 'test_matrix.npy' was not created!"
np.testing.assert_array_equal(loaded_arr, sample_arr)

print("✅ Exercise 11 Passed!")


✅ Exercise 11 Passed!


## Exercise 12: Real-World Challenge - Synthetic Image Filter 🖼️

**Background:**
In digital image processing, a grayscale image is represented as a 2D NumPy array of pixel values ranging from `0` (black) to `255` (white).

**Task:**
You are given an 8x8 synthetic image:
```python
np.random.seed(100)
img = np.random.randint(0, 256, (8, 8), dtype=np.uint8)
```
Complete the following image processing tasks:
1. **Brightening:** Create `bright_img` by scaling pixel intensities by `1.4`. Clip values so they stay within range `[0, 255]`, and cast to `np.uint8`.
2. **Binary Thresholding:** Create `binary_img` where pixels $> 128$ become `255`, and pixels $\le 128$ become `0` (dtype `np.uint8`).
3. **Horizontal Flip:** Flip `binary_img` horizontally to produce `flipped_img`.

> **Hint:** Use `np.clip()`, `np.where()`, and `np.fliplr()`.


In [48]:
np.random.seed(100)
img = np.random.randint(0, 256, (8, 8), dtype=np.uint8)

# YOUR CODE HERE
bright_img = np.clip(img*1.4, 0,255).astype(np.uint8)
binary_img = np.where(img>128, 255, 0)
flipped_img = np.fliplr(binary_img)

print("Original Image:\n", img)
print("Brightened Image:\n", bright_img)
print("Binary Image:\n", binary_img)
print("Flipped Binary Image:\n", flipped_img)


Original Image:
 [[  8 150  28 139  24 219 208 171]
 [ 67  55  67  71 103 223 123 105]
 [ 87  47 173 108  79   0 193 134]
 [176  63  67 216 138 247  10  38]
 [ 94  65  53   1 180  55  30  40]
 [ 98  39  31  31  53  80 188  47]
 [ 66  54 182 171 226 158 201  53]
 [ 14  22 107 211  34 195 230 115]]
Brightened Image:
 [[ 11 210  39 194  33 255 255 239]
 [ 93  77  93  99 144 255 172 147]
 [121  65 242 151 110   0 255 187]
 [246  88  93 255 193 255  14  53]
 [131  91  74   1 251  77  42  56]
 [137  54  43  43  74 112 255  65]
 [ 92  75 254 239 255 221 255  74]
 [ 19  30 149 255  47 255 255 161]]
Binary Image:
 [[  0 255   0 255   0 255 255 255]
 [  0   0   0   0   0 255   0   0]
 [  0   0 255   0   0   0 255 255]
 [255   0   0 255 255 255   0   0]
 [  0   0   0   0 255   0   0   0]
 [  0   0   0   0   0   0 255   0]
 [  0   0 255 255 255 255 255   0]
 [  0   0   0 255   0 255 255   0]]
Flipped Binary Image:
 [[255 255 255   0 255   0 255   0]
 [  0   0 255   0   0   0   0   0]
 [255 255   0

In [49]:
# VERIFICATION TEST 12
np.random.seed(100)
expected_img = np.random.randint(0, 256, (8, 8), dtype=np.uint8)

expected_bright = np.clip(expected_img * 1.4, 0, 255).astype(np.uint8)
expected_binary = np.where(expected_img > 128, 255, 0).astype(np.uint8)
expected_flipped = np.fliplr(expected_binary)

np.testing.assert_array_equal(bright_img, expected_bright)
np.testing.assert_array_equal(binary_img, expected_binary)
np.testing.assert_array_equal(flipped_img, expected_flipped)

print("🎉 Congratulations! All 12 Exercises Passed Successfully!")


🎉 Congratulations! All 12 Exercises Passed Successfully!
