# NumPy Fundamentals - 90 Minute Lecture
## Complete Guide with Detailed Explanations

## 1. Introduction to NumPy

**What is NumPy?**
- NumPy (Numerical Python) is the fundamental package for scientific computing in Python
- It provides a powerful N-dimensional array object (ndarray)
- It offers tools for integrating C/C++ and Fortran code
- It's the foundation for libraries like pandas, SciPy, scikit-learn, and TensorFlow

**Key Benefits:**
- **Performance**: C-level execution speeds
- **Vectorization**: No explicit loops needed
- **Memory Efficiency**: Compact, homogeneous data storage
- **Rich Functionality**: Mathematical, statistical, and linear algebra operations

In [2]:
import numpy as np
print(f"NumPy version: {np.__version__}")

# IMPORTANT: By convention, we import numpy as 'np'

NumPy version: 2.0.1


## 2. Creating Arrays

**Different Ways to Create NumPy Arrays:**
1. **np.array()**: Convert Python lists/tuples to arrays
2. **np.zeros()**: Create array filled with zeros
3. **np.ones()**: Create array filled with ones
4. **np.eye()**: Create identity matrix
5. **np.random.random()**: Create array with random values
6. **np.arange()**: Create array with evenly spaced values (like Python's range)
7. **np.linspace()**: Create array with evenly spaced values with specified number of points
8. **np.full()**: Create array filled with a constant value

**Important Notes:**
- All elements in a NumPy array must be of the same data type (homogeneous)
- The shape is defined as a tuple of dimensions (rows, columns, ...)

In [8]:
# 1. FROM LISTS: Most common way to create arrays
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array from a list
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array from nested lists

# 2. SPECIAL ARRAYS: Pre-defined arrays for specific use cases
zeros = np.zeros((3, 4))  # 3 rows, 4 columns, all zeros
ones = np.ones((2, 3))    # 2 rows, 3 columns, all ones
identity = np.eye(3)      # 3x3 identity matrix (1s on diagonal, 0s elsewhere)
random_arr = np.random.random((3, 3))  # 3x3 array with random values between 0 and 1

# 3. SEQUENCE CREATION: Useful for creating ranges of numbers
arange_arr = np.arange(0, 10, 2)  # start=0, stop=10, step=2 -> [0,2,4,6,8]
linspace_arr = np.linspace(0, 1, 5)  # 5 numbers evenly spaced between 0 and 1

# 4. CONSTANT ARRAY: Fill with a specific value
full_arr = np.full((2, 3), 7)  # 2x3 array all filled with 7

# Print all arrays to see the results
print("1D array from list:", arr1)
print("\n2D array from nested list:\n", arr2)
print("\nZeros array (3x4):\n", zeros)
print("\nOnes array (2x3):\n", ones)
print("\nIdentity matrix (3x3):\n", identity)
print("\nRandom array (3x3):\n", random_arr)
print("\nArange (0 to 10 step 2):", arange_arr)
print("\nLinspace (5 points from 0 to 1):", linspace_arr)
print("\nFull array (2x3 filled with 7):\n", full_arr)

1D array from list: [1 2 3 4 5]

2D array from nested list:
 [[1 2 3]
 [4 5 6]]

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array (3x3):
 [[0.60111501 0.70807258 0.02058449]
 [0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224]]

Arange (0 to 10 step 2): [0 2 4 6 8]

Linspace (5 points from 0 to 1): [0.   0.25 0.5  0.75 1.  ]

Full array (2x3 filled with 7):
 [[7 7 7]
 [7 7 7]]


## 3. Array Attributes and Properties

**Understanding Array Properties:**
- **shape**: Tuple showing the size of each dimension (important for reshaping)
- **ndim**: Number of dimensions (1D, 2D, 3D, etc.)
- **size**: Total number of elements in the array
- **dtype**: Data type of elements (int32, float64, bool, etc.)
- **nbytes**: Total bytes consumed by the array (useful for memory optimization)
- **itemsize**: Size of each element in bytes

**Why these properties matter:**
- Understanding shape is crucial for matrix operations
- dtype determines precision and memory usage
- ndim helps understand the array structure

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# EXPLANATION: shape returns (rows, columns)
print(f"Shape: {arr.shape}")  # (2, 3) means 2 rows and 3 columns
print(f"Dimensions: {arr.ndim}")  # 2 means 2D array
print(f"Total elements: {arr.size}")  # 2 * 3 = 6 elements
print(f"Data type: {arr.dtype}")  # int64 (64-bit integers)
print(f"Total memory: {arr.nbytes} bytes")  # 6 * 8 = 48 bytes
print(f"Each element size: {arr.itemsize} bytes")  # 8 bytes per element

Shape: (2, 3)
Dimensions: 2
Total elements: 6
Data type: int64
Total memory: 48 bytes
Each element size: 8 bytes


## 4. Array Operations (Element-wise)

**Key Concept: Element-wise Operations**
- NumPy performs operations element-by-element automatically
- This is called **vectorization** and is much faster than Python loops
- All arithmetic operations work on corresponding elements

**Available Operations:**
1. **Arithmetic**: +, -, *, /, ** (power), % (modulus)
2. **Trigonometric**: sin, cos, tan, arcsin, arccos, arctan
3. **Exponential/Log**: exp, log, log10, log2
4. **Rounding**: round, floor, ceil, trunc
5. **Absolute**: abs, absolute
6. **Other**: sqrt (square root), square, reciprocal

**Important Note:**
- These operations create new arrays (they don't modify the original)
- To modify in-place, use functions like np.add(), np.multiply() with the 'out' parameter

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# EXPLANATION: These operations work element by element
# a + b -> [1+5, 2+6, 3+7, 4+8] = [6,8,10,12]
print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (a / b):", a / b)
print("Power (a ** 2):", a ** 2)  # Square each element
print("Modulus (b % 3):", b % 3)  # Remainder when divided by 3

# Mathematical functions
print("\nSquare root of a:", np.sqrt(a))
print("Exponential (e^a):", np.exp(a))
print("Natural log (ln a):", np.log(a))  # Natural logarithm
print("Log base 10:", np.log10(a))
print("Sin of a (in radians):", np.sin(a))
print("Absolute value:", np.abs([-1, -2, -3, -4]))
print("Rounded values:", np.round(np.array([1.234, 2.567, 3.891]), 2))  # 2 decimal places

Addition (a + b): [ 6  8 10 12]
Subtraction (a - b): [-4 -4 -4 -4]
Multiplication (a * b): [ 5 12 21 32]
Division (a / b): [0.2        0.33333333 0.42857143 0.5       ]
Power (a ** 2): [ 1  4  9 16]
Modulus (b % 3): [2 0 1 2]

Square root of a: [1.         1.41421356 1.73205081 2.        ]
Exponential (e^a): [ 2.71828183  7.3890561  20.08553692 54.59815003]
Natural log (ln a): [0.         0.69314718 1.09861229 1.38629436]
Log base 10: [0.         0.30103    0.47712125 0.60205999]
Sin of a (in radians): [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Absolute value: [1 2 3 4]
Rounded values: [1.23 2.57 3.89]


## 5. Matrix Operations

**Matrix Operations vs Element-wise Operations:**
- **Element-wise**: * (star) operator does element-wise multiplication
- **Matrix Multiplication**: @ operator or np.dot() does proper matrix multiplication
- **Important**: Matrix multiplication requires dimensions to match (columns of first = rows of second)

**Linear Algebra Functions:**
- **np.linalg.inv()**: Matrix inverse (only for square, non-singular matrices)
- **np.linalg.det()**: Determinant
- **np.linalg.eig()**: Eigenvalues and eigenvectors
- **np.linalg.solve()**: Solve linear equation Ax = b
- **np.linalg.matrix_rank()**: Rank of matrix
- **np.linalg.norm()**: Matrix or vector norm

In [11]:
A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
B = np.array([[5, 6], [7, 8]])  # 2x2 matrix

# EXPLANATION: Matrix multiplication vs element-wise multiplication
# Element-wise multiplication (a11*b11, a12*b12, ...)
print("Element-wise (A * B):\n", A * B)

# Matrix multiplication (proper linear algebra)
# Formula: result[i,j] = sum_k A[i,k] * B[k,j]
print("\nMatrix multiplication (A @ B):\n", A @ B)
print("Matrix multiplication alternative (np.dot):\n", np.dot(A, B))

# Transpose (swap rows and columns)
print("\nTranspose (A.T):\n", A.T)  # Rows become columns

# Inverse (only exists for square matrices with non-zero determinant)
try:
    inv_A = np.linalg.inv(A)
    print("\nInverse (A_inv):\n", inv_A)
    # Verify inverse: A * A_inv should be identity matrix
    print("\nVerification (A @ A_inv):\n", A @ inv_A)  # Should be identity
except np.linalg.LinAlgError:
    print("Matrix is not invertible (singular)")

# Determinant (scalar value that indicates if matrix is invertible)
det = np.linalg.det(A)
print(f"\nDeterminant: {det}")  # If det=0, matrix is singular

# Eigenvalues and eigenvectors (important in PCA, dimension reduction)
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors (columns):\n{eigenvectors}")

# Solving linear equations: 2x + 3y = 8, 4x + 5y = 14
# Matrix form: A_coeff * x_vector = b_vector
A_coeff = np.array([[2, 3], [4, 5]])
b_vector = np.array([8, 14])
solution = np.linalg.solve(A_coeff, b_vector)
print(f"\nSolution to 2x+3y=8, 4x+5y=14: x={solution[0]}, y={solution[1]}")
print(f"Verification: 2*{solution[0]} + 3*{solution[1]} = {2*solution[0] + 3*solution[1]}")

Element-wise (A * B):
 [[ 5 12]
 [21 32]]

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]]
Matrix multiplication alternative (np.dot):
 [[19 22]
 [43 50]]

Transpose (A.T):
 [[1 3]
 [2 4]]

Inverse (A_inv):
 [[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A @ A_inv):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Determinant: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors (columns):
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Solution to 2x+3y=8, 4x+5y=14: x=1.0, y=2.0
Verification: 2*1.0 + 3*2.0 = 8.0


## 6. Vectorization (No Loops!)

**What is Vectorization?**
- Performing operations on entire arrays without explicit Python loops
- NumPy uses optimized C code to process all elements simultaneously
- This is the KEY performance advantage of NumPy

**Why Vectorization Matters:**
- Much faster than Python loops (10-100x speedup)
- Code is more concise and readable
- Less prone to bugs (no index errors)
- Uses CPU's vector processing capabilities (SIMD)

**Vectorized Operations:**
- All arithmetic operations are vectorized
- np.where() for conditional operations
- Boolean indexing for filtering
- Universal functions (ufuncs) like np.sin, np.exp, etc.

In [12]:
# EXPLANATION: Compare Python loop vs Vectorized operation
def square_loop(arr):
    # Python loop - slow because it's interpreted
    result = []
    for x in arr:
        result.append(x ** 2)
    return result

def square_vectorized(arr):
    # Vectorized - fast because it's compiled C code
    return arr ** 2

data = np.arange(1000)

# Time comparison (using %timeit magic command)
print("Timing Python loop:")
%timeit square_loop(data)
print("\nTiming Vectorized operation:")
%timeit square_vectorized(data)

# EXPLANATION: np.where() - conditional element selection
# Syntax: np.where(condition, value_if_true, value_if_false)
arr = np.array([1, 2, 3, 4, 5])
print("\nOriginal array:", arr)
print("Where arr > 3 (keep value, else 0):", np.where(arr > 3, arr, 0))
print("Where arr % 2 == 0 (label even/odd):", np.where(arr % 2 == 0, 'even', 'odd'))

# Vectorized mathematical functions
x = np.linspace(0, 2*np.pi, 10)  # 10 points from 0 to 2π
print(f"\nVectorized sin: {np.sin(x)}")  # Applies sin to all elements

# Boolean indexing with vectorized operations
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\nEven numbers (arr % 2 == 0):", arr[arr % 2 == 0])
print("Numbers between 3 and 7:", arr[(arr > 3) & (arr < 7)])
print("Numbers NOT between 3 and 7:", arr[(arr <= 3) | (arr >= 7)])

# Vectorized operations on multiple conditions
grades = np.array([85, 45, 78, 92, 62, 55])
grade_labels = np.where(grades >= 70, 'Pass', 'Fail')
print(f"\nGrades: {grades}")
print(f"Pass/Fail: {grade_labels}")

Timing Python loop:
157 µs ± 46.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

Timing Vectorized operation:
1.58 µs ± 391 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

Original array: [1 2 3 4 5]
Where arr > 3 (keep value, else 0): [0 0 0 4 5]
Where arr % 2 == 0 (label even/odd): ['odd' 'even' 'odd' 'even' 'odd']

Vectorized sin: [ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]

Even numbers (arr % 2 == 0): [ 2  4  6  8 10]
Numbers between 3 and 7: [4 5 6]
Numbers NOT between 3 and 7: [ 1  2  3  7  8  9 10]

Grades: [85 45 78 92 62 55]
Pass/Fail: ['Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail']


## 7. Indexing and Slicing

**Indexing Basics:**
- NumPy indexing is similar to Python lists but more powerful
- 0-based indexing (first element is at index 0)
- Negative indices count from the end (-1 is last element)
- Colon : creates a slice (start:stop:step)

**Types of Indexing:**
1. **Basic Indexing**: Single element access (arr[0], arr[2,1])
2. **Slicing**: Access subarrays (arr[1:5:2])
3. **Boolean Indexing**: Using conditions (arr[arr > 5])
4. **Fancy Indexing**: Using integer arrays (arr[[0,2,4]])
5. **Multi-dimensional**: arr[row_slice, col_slice]

**Important:**
- Slices return VIEWS (not copies) - modifying slice modifies original
- Use .copy() to create a copy
- In 2D: arr[row_index, col_index]

In [13]:
# 1D ARRAY INDEXING
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("1D Array:", arr)
print("\n--- Basic Indexing ---")
print("First element (arr[0]):", arr[0])
print("Last element (arr[-1]):", arr[-1])
print("Third element (arr[2]):", arr[2])

print("\n--- Slicing (arr[start:stop:step]) ---")
print("Elements 1 to 4 (arr[1:5]):", arr[1:5])  # Index 1 to 4
print("First three (arr[:3]):", arr[:3])
print("From index 3 to end (arr[3:]):", arr[3:])
print("Every second element (arr[::2]):", arr[::2])
print("Reverse array (arr[::-1]):", arr[::-1])

# 2D ARRAY INDEXING
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\n2D Matrix (3x4):\n", matrix)
print("\n--- 2D Indexing (row, column) ---")
print("Element at row 1, column 2 (matrix[1,2]):", matrix[1, 2])  # 7
print("Row 1 (matrix[1, :]):", matrix[1, :])  # All columns of row 1
print("Column 2 (matrix[:, 2]):", matrix[:, 2])  # All rows of column 2
print("Submatrix rows 0-1, cols 1-2:\n", matrix[:2, 1:3])

# FANCY INDEXING (using integer arrays)
print("\n--- Fancy Indexing ---")
indices = [0, 2, 4]  # Indices to select
print(f"Select elements at indices {indices} from arr:", arr[indices])

# BOOLEAN INDEXING (using conditions)
print("\n--- Boolean Indexing ---")
bool_mask = matrix > 6
print("Boolean mask (matrix > 6):\n", bool_mask)
print("Values > 6:", matrix[bool_mask])

# MODIFYING VALUES with indexing
print("\n--- Modifying Values ---")
matrix_copy = matrix.copy()  # Create copy to not modify original
matrix_copy[1, 1] = 100  # Change single element
print("After changing (1,1) to 100:\n", matrix_copy)
matrix_copy[matrix_copy > 5] = 999  # Replace all > 5 with 999
print("After replacing all > 5 with 999:\n", matrix_copy)

1D Array: [10 20 30 40 50 60 70 80]

--- Basic Indexing ---
First element (arr[0]): 10
Last element (arr[-1]): 80
Third element (arr[2]): 30

--- Slicing (arr[start:stop:step]) ---
Elements 1 to 4 (arr[1:5]): [20 30 40 50]
First three (arr[:3]): [10 20 30]
From index 3 to end (arr[3:]): [40 50 60 70 80]
Every second element (arr[::2]): [10 30 50 70]
Reverse array (arr[::-1]): [80 70 60 50 40 30 20 10]

2D Matrix (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

--- 2D Indexing (row, column) ---
Element at row 1, column 2 (matrix[1,2]): 7
Row 1 (matrix[1, :]): [5 6 7 8]
Column 2 (matrix[:, 2]): [ 3  7 11]
Submatrix rows 0-1, cols 1-2:
 [[2 3]
 [6 7]]

--- Fancy Indexing ---
Select elements at indices [0, 2, 4] from arr: [10 30 50]

--- Boolean Indexing ---
Boolean mask (matrix > 6):
 [[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
Values > 6: [ 7  8  9 10 11 12]

--- Modifying Values ---
After changing (1,1) to 100:
 [[  1   2   3   4]
 [  5 100   

## 8. Reshaping Arrays

**Reshaping Methods:**
1. **reshape()**: Change shape without changing data (returns view if possible)
2. **flatten()**: Returns a 1D copy of the array
3. **ravel()**: Returns a 1D view (not a copy)
4. **T / transpose()**: Swaps dimensions (rows <-> columns)

**Important Notes:**
- Total number of elements must remain the same
- Use -1 to auto-calculate a dimension (np.reshape(2, -1))
- reshape() vs resize(): reshape returns new array, resize modifies in-place

**Stacking/Splitting:**
- **np.vstack()**: Stack arrays vertically (row-wise)
- **np.hstack()**: Stack arrays horizontally (column-wise)
- **np.split()**: Split array into multiple sub-arrays

In [ ]:
arr = np.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print("Original array:", arr)

print("\n--- Reshaping ---")
# EXPLANATION: reshape changes dimensions but keeps the same data
reshaped = arr.reshape(3, 4)  # 3 rows, 4 columns
print("Reshaped (3x4):\n", reshaped)

# Auto-calculate one dimension with -1
auto_reshape = arr.reshape(2, -1)  # 2 rows, auto columns (6 columns)
print("Auto reshape (2x6):\n", auto_reshape)

print("\n--- Flattening ---")
#! flatten() returns a copy, ravel() returns a view (faster)
print("Flatten (copy):", reshaped.flatten())
print("Ravel (view):", reshaped.ravel())

print("\n--- Transpose ---")
# Transpose swaps rows and columns
print("Original (3x4):\n", reshaped)
print("Transposed (4x3):\n", reshaped.T)

print("\n--- Stacking Arrays ---")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
print("a:", a)
print("b:", b)
print("Vertical stack (vstack):\n", np.vstack([a, b, c]))  # Stack as rows
print("Horizontal stack (hstack):", np.hstack([a, b, c]))  # Stack as columns

print("\n--- Splitting Arrays ---")
arr = np.arange(10)
print("Array to split:", arr)
# Split at positions 3 and 7
split_parts = np.split(arr, [3, 7])
print("Split at [3, 7]:", split_parts)  # [0-2], [3-6], [7-9]

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

--- Reshaping ---
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Auto reshape (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

--- Flattening ---
Flatten (copy): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel (view): [ 0  1  2  3  4  5  6  7  8  9 10 11]

--- Transpose ---
Original (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed (4x3):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

--- Stacking Arrays ---
a: [1 2 3]
b: [4 5 6]
Vertical stack (vstack):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Horizontal stack (hstack): [1 2 3 4 5 6 7 8 9]

--- Splitting Arrays ---
Array to split: [0 1 2 3 4 5 6 7 8 9]
Split at [3, 7]: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


## 9. Statistical Operations

**Statistical Functions:**
- **Central Tendency**: mean, median, mode (via scipy)
- **Dispersion**: std (standard deviation), var (variance), ptp (peak-to-peak)
- **Distribution**: percentile, quantile, min, max
- **Summation**: sum, cumsum (cumulative sum), cumprod (cumulative product)

**Axis Parameter (Important!):**
- **axis=0**: Operates along columns (down the rows) - reduces number of rows
- **axis=1**: Operates along rows (across the columns) - reduces number of columns
- Default (no axis): Operates on entire array

**Matrix Statistics:**
- **np.cov()**: Covariance matrix
- **np.corrcoef()**: Correlation matrix
- **np.histogram()**: Frequency distribution

In [15]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Data:", data)
print("\n--- Basic Statistics (1D) ---")
print(f"Mean (average): {np.mean(data)}")
print(f"Median (middle value): {np.median(data)}")
print(f"Standard deviation (spread): {np.std(data):.2f}")
print(f"Variance (std²): {np.var(data):.2f}")
print(f"Sum (total): {np.sum(data)}")
print(f"Min (smallest): {np.min(data)}")
print(f"Max (largest): {np.max(data)}")
print(f"Range (max-min): {np.ptp(data)}")
print(f"25th percentile: {np.percentile(data, 25)}")
print(f"75th percentile: {np.percentile(data, 75)}")
print(f"Cumulative sum: {np.cumsum(data)}")  # Running total

print("\n--- 2D Matrix Statistics (axis parameter) ---")
print("Matrix:\n", matrix)
print("\nEXPLANATION: axis=0 (down rows) - calculate per column")
print("Column means (axis=0):", np.mean(matrix, axis=0))  # Mean of each column
print("Column sums (axis=0):", np.sum(matrix, axis=0))
print("Column max (axis=0):", np.max(matrix, axis=0))

print("\nEXPLANATION: axis=1 (across columns) - calculate per row")
print("Row means (axis=1):", np.mean(matrix, axis=1))  # Mean of each row
print("Row sums (axis=1):", np.sum(matrix, axis=1))
print("Row max (axis=1):", np.max(matrix, axis=1))

print("\n--- Correlation and Covariance ---")
# Two related variables
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])  # y = 2*x (perfect correlation)
z = np.array([10, 8, 6, 4, 2])   # Negative correlation with x

print("Covariance matrix (x, y):\n", np.cov(x, y))
print("Correlation matrix (x, y):\n", np.corrcoef(x, y))  # Should be ~1.0
print("Correlation (x, z):\n", np.corrcoef(x, z))  # Should be ~-1.0

Data: [ 1  2  3  4  5  6  7  8  9 10]

--- Basic Statistics (1D) ---
Mean (average): 5.5
Median (middle value): 5.5
Standard deviation (spread): 2.87
Variance (std²): 8.25
Sum (total): 55
Min (smallest): 1
Max (largest): 10
Range (max-min): 9
25th percentile: 3.25
75th percentile: 7.75
Cumulative sum: [ 1  3  6 10 15 21 28 36 45 55]

--- 2D Matrix Statistics (axis parameter) ---
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

EXPLANATION: axis=0 (down rows) - calculate per column
Column means (axis=0): [4. 5. 6.]
Column sums (axis=0): [12 15 18]
Column max (axis=0): [7 8 9]

EXPLANATION: axis=1 (across columns) - calculate per row
Row means (axis=1): [2. 5. 8.]
Row sums (axis=1): [ 6 15 24]
Row max (axis=1): [3 6 9]

--- Correlation and Covariance ---
Covariance matrix (x, y):
 [[ 2.5  5. ]
 [ 5.  10. ]]
Correlation matrix (x, y):
 [[1. 1.]
 [1. 1.]]
Correlation (x, z):
 [[ 1. -1.]
 [-1.  1.]]


## 10. Performance: NumPy vs Python Lists

**Why NumPy is Faster:**
1. **Compiled C Code**: Operations are executed in C, not Python
2. **Memory Efficiency**: Contiguous memory layout with no overhead
3. **Vectorization**: Single instruction, multiple data (SIMD) operations
4. **No Type Checking**: Homogeneous data types reduce runtime checks
5. **Cache Optimization**: Better cache utilization with contiguous data

**Memory Comparison:**
- Python list: Stores pointers to Python objects (28 bytes per int + pointer)
- NumPy array: Stores raw C data types (8 bytes per float64)
- For large datasets, NumPy can be 4-8x more memory efficient

In [16]:
import time

# Create large dataset (10 million elements)
size = 10**7
print(f"Creating data with {size:,} elements...")

# Python list vs NumPy array
list_data = list(range(size))
array_data = np.arange(size)

print("\n--- Performance Comparison (element-wise multiplication) ---")

# Python list operation (using list comprehension)
start = time.time()
list_result = [x * 2 for x in list_data]
list_time = time.time() - start
print(f"Python list time: {list_time:.2f} seconds")

# NumPy array operation (vectorized)
start = time.time()
array_result = array_data * 2
array_time = time.time() - start
print(f"NumPy array time: {array_time:.2f} seconds")

# Performance ratio
speedup = list_time / array_time
print(f"\nNumPy is {speedup:.1f}x faster!")

print("\n--- Memory Comparison ---")
# Memory calculation
import sys
list_memory = sys.getsizeof(list_data)  # This only shows list object memory
# For more accurate: each integer is ~28 bytes
list_total_memory = list_memory + size * 28
array_memory = array_data.nbytes

print(f"Python list memory: ~{list_total_memory/1024/1024:.2f} MB")
print(f"NumPy array memory: {array_memory/1024/1024:.2f} MB")
print(f"Memory savings: {list_total_memory/array_memory:.1f}x smaller")

Creating data with 10,000,000 elements...

--- Performance Comparison (element-wise multiplication) ---
Python list time: 0.58 seconds
NumPy array time: 0.03 seconds

NumPy is 18.4x faster!

--- Memory Comparison ---
Python list memory: ~343.32 MB
NumPy array memory: 76.29 MB
Memory savings: 4.5x smaller


## 11. Advanced: Broadcasting

**What is Broadcasting?**
- Broadcasting allows NumPy to work with arrays of different shapes
- The smaller array is "broadcasted" to match the shape of the larger array
- This eliminates the need to explicitly expand arrays

**Broadcasting Rules:**
1. Arrays must have same number of dimensions, OR
2. Arrays are compatible if dimensions are equal OR one is 1
3. The resulting array has the maximum dimension of either input

**Common Use Cases:**
- Adding a constant to all elements: arr + 5 (scalar broadcasting)
- Adding a row/column vector to a matrix
- Normalization (subtracting mean, dividing by std)
- Creating coordinate grids

In [5]:
# EXPLANATION: Broadcasting enables operations with different shapes
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
B = np.array([10, 20, 30])  # Shape (3,)

print("Matrix A (2x3):\n", A)
print("Vector B (3,):", B)
print("\n--- Broadcasting Example: Add row vector to matrix ---")
# B is broadcasted to shape (2,3) by repeating the row twice
print("A + B:\n", A + B)
print("\nBroadcasted B (conceptually):\n", np.array([[10,20,30], [10,20,30]]))

C = np.array([[10], [20], [30]])  # Shape (3, 1)
print("\nMatrix A (2x3):\n", A)
print("Vector C (3x1):\n", C)
print("\n--- Broadcasting Example: Add column vector to matrix ---")
# C is broadcasted to shape (2,3) by repeating the column twice
# print("A + C:\n", A + C)

print("\n--- Scalar Broadcasting ---")
print("A * 2:\n", A * 2)  # Scalar 2 broadcasts to entire array
print("A + 5:\n", A + 5)

print("\n--- Practical Use Case: Data Normalization ---")
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Original data:\n", data)

# Subtract column means (broadcasting across rows)
col_means = np.mean(data, axis=0)  # Shape (3,)
data_centered = data - col_means  # Broadcasts to (4,3)
print("\nColumn means:", col_means)
print("Data centered (mean subtracted):\n", data_centered)

# Standardize (subtract mean, divide by std)
col_std = np.std(data, axis=0)
data_standardized = (data - col_means) / col_std
print("\nColumn std:", col_std)
print("Data standardized (z-scores):\n", data_standardized)

print("\n--- Broadcasting Rules Summary ---")
print("Rule 1: Arrays with same shape -> element-wise operation")
print("Rule 2: Arrays with different shapes but compatible -> broadcast")
print("Rule 3: If dimensions are (1) -> expands to match")
print("Rule 4: If dimensions don't match and neither is 1 -> error")

Matrix A (2x3):
 [[1 2 3]
 [4 5 6]]
Vector B (3,): [10 20 30]

--- Broadcasting Example: Add row vector to matrix ---
A + B:
 [[11 22 33]
 [14 25 36]]

Broadcasted B (conceptually):
 [[10 20 30]
 [10 20 30]]

Matrix A (2x3):
 [[1 2 3]
 [4 5 6]]
Vector C (3x1):
 [[10]
 [20]
 [30]]

--- Broadcasting Example: Add column vector to matrix ---

--- Scalar Broadcasting ---
A * 2:
 [[ 2  4  6]
 [ 8 10 12]]
A + 5:
 [[ 6  7  8]
 [ 9 10 11]]

--- Practical Use Case: Data Normalization ---
Original data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Column means: [5.5 6.5 7.5]
Data centered (mean subtracted):
 [[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]

Column std: [3.35410197 3.35410197 3.35410197]
Data standardized (z-scores):
 [[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]

--- Broadcasting Rules Summary ---
Rule 1: Arrays with same shape -> element-wi

## 12. Random Number Generation

**Random Functions:**
- **np.random.seed()**: Set random seed for reproducibility
- **np.random.random()**: Uniform distribution [0, 1)
- **np.random.randn()**: Standard normal distribution (mean=0, std=1)
- **np.random.randint()**: Random integers in a range
- **np.random.uniform()**: Uniform distribution over any interval
- **np.random.binomial()**: Binomial distribution
- **np.random.exponential()**: Exponential distribution
- **np.random.choice()**: Random sampling from an array
- **np.random.permutation()**: Random permutation of array elements

**Why Set a Seed?**
- Ensures reproducibility in research
- Debugging (same results each run)
- For demonstration purposes

In [6]:
# EXPLANATION: Seed ensures reproducibility
# Same seed -> same random numbers
np.random.seed(42)  # 42 is arbitrary - can be any integer

print("--- Different Random Distributions ---")
print("Uniform [0,1) (continuous):", np.random.random(5))
print("Standard Normal (mean=0, std=1):", np.random.randn(5))
print("Uniform [10,20] (continuous):", np.random.uniform(10, 20, 5))
print("Integers [0,10) (discrete):", np.random.randint(0, 10, 5))
print("Integers [0,10] (inclusive):", np.random.randint(0, 10+1, 5))
print("Binomial (n=10, p=0.5):", np.random.binomial(10, 0.5, 5))
print("Exponential (scale=1):", np.random.exponential(1, 5))

print("\n--- Random Permutation ---")
arr = np.arange(10)
print("Original:", arr)
print("Permuted (shuffled):", np.random.permutation(arr))

print("\n--- Random Sampling ---")
population = np.arange(100)
sample = np.random.choice(population, size=10, replace=False)
print(f"Sample of 10 without replacement: {sample}")
sample_with_replacement = np.random.choice(population, size=10, replace=True)
print(f"Sample of 10 with replacement: {sample_with_replacement}")

print("\n--- Practical Use: Creating Random Matrices ---")
random_matrix = np.random.randn(3, 4)  # 3x4 matrix from normal distribution
print("Random 3x4 matrix from normal distribution:\n", random_matrix)
print(f"Mean: {np.mean(random_matrix):.3f}, Std: {np.std(random_matrix):.3f}")

# Another seed demonstration
print("\n--- Seed Demonstration ---")
np.random.seed(123)
print("With seed=123:", np.random.random(3))
np.random.seed(123)
print("With seed=123 again:", np.random.random(3))  # Same sequence
np.random.seed(456)
print("With different seed=456:", np.random.random(3))  # Different sequence

--- Different Random Distributions ---
Uniform [0,1) (continuous): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Standard Normal (mean=0, std=1): [ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017]
Uniform [10,20] (continuous): [15.24756432 14.31945019 12.9122914  16.11852895 11.39493861]
Integers [0,10) (discrete): [2 6 3 8 2]
Integers [0,10] (inclusive): [4 2 6 4 8]
Binomial (n=10, p=0.5): [3 8 8 6 4]
Exponential (scale=1): [0.10277732 1.15275076 0.58009084 0.13015223 0.68354723]

--- Random Permutation ---
Original: [0 1 2 3 4 5 6 7 8 9]
Permuted (shuffled): [8 9 5 4 6 7 1 3 0 2]

--- Random Sampling ---
Sample of 10 without replacement: [80 46 50 55 95 29  1 51  5 37]
Sample of 10 with replacement: [ 5 27 27 43 83 29 61 74 91 88]

--- Practical Use: Creating Random Matrices ---
Random 3x4 matrix from normal distribution:
 [[-0.92408284 -0.70205309 -0.32766215 -0.39210815]
 [-1.46351495  0.29612028  0.26105527  0.00511346]
 [-0.23458713 -1.41537074 -0.42064532 -

## 13. Advanced Operations: Universal Functions (ufuncs)

**What are ufuncs?**
- Universal functions are functions that operate element-wise on arrays
- They are implemented in compiled C for maximum performance
- They support broadcasting, casting, and type checking

**Types of ufuncs:**
1. **Math**: add, subtract, multiply, divide, power, remainder
2. **Trigonometric**: sin, cos, tan, arcsin, arccos, arctan
3. **Hyperbolic**: sinh, cosh, tanh
4. **Exponential/Log**: exp, expm1, log, log10, log2, log1p
5. **Comparison**: greater, less, equal, not_equal
6. **Logical**: logical_and, logical_or, logical_not
7. **Reduction**: sum, prod, mean, std, var (reduce operations)

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

print("\n--- Cumulative Operations ---")
print("Cumulative sum (running total):", np.cumsum(arr))  # [1, 1+2, 1+2+3, ...]
print("Cumulative product:", np.cumprod(arr))  # [1, 1*2, 1*2*3, ...]
print("Difference (consecutive differences):", np.diff(arr))  # [2-1, 3-2, ...]
print("Gradient (rate of change):", np.gradient(arr))

print("\n--- Comparison Operators (ufuncs) ---")
arr = np.array([1, 3, 5, 7, 9])
print("Array:", arr)
print("Arr == 3:", arr == 3)  # Element-wise equality check
print("Arr > 4:", arr > 4)
print("Arr < 6:", arr < 6)
print("Arr >= 5:", arr >= 5)
print("Arr != 5:", arr != 5)

print("\n--- Logical Operations ---")
a = np.array([True, False, True, False])
b = np.array([False, False, True, True])
print("a:", a)
print("b:", b)
print("Logical AND (a & b):", np.logical_and(a, b))
print("Logical OR (a | b):", np.logical_or(a, b))
print("Logical XOR (a ^ b):", np.logical_xor(a, b))
print("Logical NOT (~a):", np.logical_not(a))

print("\n--- Aggregation Functions (Reductions) ---")
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Product:", np.prod(arr))
print("All elements > 0?:", np.all(arr > 0))
print("Any element > 40?:", np.any(arr > 40))
print("Argmax (index of max):", np.argmax(arr))  # Index of maximum
print("Argmin (index of min):", np.argmin(arr))  # Index of minimum

print("\n--- Vectorized Conditions ---")
# Multiple conditions using logical operators
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = (arr > 3) & (arr < 8)  # Both conditions must be true
print(f"Numbers between 3 and 8: {arr[mask]}")
mask = (arr <= 3) | (arr >= 8)  # Either condition can be true
print(f"Numbers <= 3 or >= 8: {arr[mask]}")

Original array: [1 2 3 4 5]

--- Cumulative Operations ---
Cumulative sum (running total): [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]
Difference (consecutive differences): [1 1 1 1]
Gradient (rate of change): [1. 1. 1. 1. 1.]

--- Comparison Operators (ufuncs) ---
Array: [1 3 5 7 9]
Arr == 3: [False  True False False False]
Arr > 4: [False False  True  True  True]
Arr < 6: [ True  True  True False False]
Arr >= 5: [False False  True  True  True]
Arr != 5: [ True  True False  True  True]

--- Logical Operations ---
a: [ True False  True False]
b: [False False  True  True]
Logical AND (a & b): [False False  True False]
Logical OR (a | b): [ True False  True  True]
Logical XOR (a ^ b): [ True False False  True]
Logical NOT (~a): [False  True False  True]

--- Aggregation Functions (Reductions) ---
Array: [10 20 30 40 50]
Sum: 150
Product: 12000000
All elements > 0?: True
Any element > 40?: True
Argmax (index of max): 4
Argmin (index of min): 0

--- Vectorized Conditions --

## 14. Working with Missing Data (NaN)

**NaN (Not a Number):**
- Represents missing or undefined values
- Propagates through operations (np.nan + 5 = np.nan)
- Special functions to handle NaNs:
  - **np.isnan()**: Check for NaN values
  - **np.nan_to_num()**: Replace NaN with a number
  - **np.nanmean()**, **np.nanstd()**, **np.nansum()**: Ignore NaNs in calculations

In [18]:
# Create array with NaN values
arr = np.array([1, 2, np.nan, 4, 5, np.nan, 7])
print("Array with NaN values:", arr)

print("\n--- Detecting NaN ---")
# isNaN returns boolean array
nan_mask = np.isnan(arr)
print("Is NaN?:", nan_mask)
print(f"Number of NaN values: {np.sum(nan_mask)}")
print(f"Valid values: {arr[~nan_mask]}")  # ~ is NOT operator

print("\n--- Operations with NaN ---")
print("Standard mean (returns NaN):", np.mean(arr))  # NaN propagates
print("Mean ignoring NaN:", np.nanmean(arr))  # 1+2+4+5+7 / 5
print("Sum ignoring NaN:", np.nansum(arr))
print("Std ignoring NaN:", np.nanstd(arr))
print("Median ignoring NaN:", np.nanmedian(arr))

print("\n--- Replacing NaN ---")
# Replace NaN with a specific value
arr_filled = np.nan_to_num(arr, nan=0)
print("Replace NaN with 0:", arr_filled)

# Alternative: replace with mean
mean_val = np.nanmean(arr)
arr_mean_filled = np.where(np.isnan(arr), mean_val, arr)
print(f"Replace NaN with mean ({mean_val:.2f}):", arr_mean_filled)

print("\n--- Remove NaN completely ---")
arr_no_nan = arr[~np.isnan(arr)]
print("Remove all NaN values:", arr_no_nan)

Array with NaN values: [ 1.  2. nan  4.  5. nan  7.]

--- Detecting NaN ---
Is NaN?: [False False  True False False  True False]
Number of NaN values: 2
Valid values: [1. 2. 4. 5. 7.]

--- Operations with NaN ---
Standard mean (returns NaN): nan
Mean ignoring NaN: 3.8
Sum ignoring NaN: 19.0
Std ignoring NaN: 2.1354156504062622
Median ignoring NaN: 4.0

--- Replacing NaN ---
Replace NaN with 0: [1. 2. 0. 4. 5. 0. 7.]
Replace NaN with mean (3.80): [1.  2.  3.8 4.  5.  3.8 7. ]

--- Remove NaN completely ---
Remove all NaN values: [1. 2. 4. 5. 7.]


## 15. Saving and Loading Arrays

**File Formats:**
1. **.npy**: NumPy's binary format (fast, efficient, preserves dtype)
2. **.npz**: Compressed archive of multiple arrays
3. **Text files**: CSV, TSV, etc. (human-readable, but slower)

**Functions:**
- **np.save()**: Save single array
- **np.savez()**: Save multiple arrays in compressed format
- **np.load()**: Load saved arrays
- **np.savetxt()**: Save to text file
- **np.loadtxt()**: Load from text file

**When to use which:**
- .npy: For fast I/O and preserving array structure
- .npz: For multiple arrays in one file
- Text: For interoperability with other software

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)

print("\n--- Saving Single Array (.npy) ---")
# Save to binary format (fast, efficient)
np.save('my_array.npy', arr)
print("Saved to 'my_array.npy'")

# Load back
loaded = np.load('my_array.npy')
print("Loaded array:\n", loaded)

print("\n--- Saving Multiple Arrays (.npz) ---")
# Save multiple arrays in one file
np.savez('multiple_arrays.npz',
         array1=arr,
         array2=np.array([10, 20, 30]),
         array3=np.eye(3))
print("Saved multiple arrays to 'multiple_arrays.npz'")

# Load all arrays
data = np.load('multiple_arrays.npz')
print("\nLoaded from .npz:")
for key in data.keys():
    print(f"{key}:\n{data[key]}")

print("\n--- Saving as Text (CSV) ---")
# Save as human-readable text
np.savetxt('array.csv', arr, delimiter=',', fmt='%d')
print("Saved as 'array.csv'")

# Load from text
loaded_txt = np.loadtxt('array.csv', delimiter=',')
print("Loaded from CSV:\n", loaded_txt)

print("\n--- Compressed .npz (smaller file) ---")
np.savez_compressed('compressed_arrays.npz',
                   big_array=np.random.rand(1000, 1000))
print("Saved compressed .npz file")

Original array:
 [[1 2 3]
 [4 5 6]]

--- Saving Single Array (.npy) ---
Saved to 'my_array.npy'
Loaded array:
 [[1 2 3]
 [4 5 6]]

--- Saving Multiple Arrays (.npz) ---
Saved multiple arrays to 'multiple_arrays.npz'

Loaded from .npz:
array1:
[[1 2 3]
 [4 5 6]]
array2:
[10 20 30]
array3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--- Saving as Text (CSV) ---
Saved as 'array.csv'
Loaded from CSV:
 [[1. 2. 3.]
 [4. 5. 6.]]

--- Compressed .npz (smaller file) ---
Saved compressed .npz file


## 16. Real-World Example: Image Processing

**Image as NumPy Array:**
- Grayscale image: 2D array (height x width) with values 0-255
- Color image: 3D array (height x width x 3) for RGB channels
- Processing images becomes efficient matrix operations

**Common Operations:**
1. **Brightness**: Multiply or add to all pixels
2. **Contrast**: Scale pixel values
3. **Filtering**: Convolution with kernels (blur, sharpen, edge detection)
4. **Thresholding**: Convert to binary (black/white)
5. **Histogram**: Statistical distribution of pixel values

In [8]:
# Create a synthetic grayscale image (8x8 pixels)
np.random.seed(42)
image = np.random.randint(0, 256, (8, 8), dtype=np.uint8)
print("Original Image (8x8 pixel values):\n", image)

print("\n--- Image Processing Operations ---")

# 1. Brightness adjustment
print("\n1. Brightness Adjustment (multiply by 1.5):")
bright_image = np.clip(image * 1.5, 0, 255).astype(np.uint8)
print(bright_image)
print(f"Original mean: {np.mean(image):.2f}")
print(f"Bright mean: {np.mean(bright_image):.2f}")

# 2. Contrast enhancement
print("\n2. Contrast Enhancement (stretch to full range):")
min_val = np.min(image)
max_val = np.max(image)
contrast_image = ((image - min_val) / (max_val - min_val) * 255).astype(np.uint8)
print(contrast_image)
print(f"Original range: {min_val} - {max_val}")
print(f"Contrast range: {np.min(contrast_image)} - {np.max(contrast_image)}")

# 3. Thresholding (binary image)
print("\n3. Thresholding (pixels > 127 become white):")
threshold = 127
binary_image = np.where(image > threshold, 255, 0).astype(np.uint8)
print(binary_image)

# 4. Image statistics
print("\n4. Image Statistics:")
print(f"Mean: {np.mean(image):.2f}")
print(f"Std: {np.std(image):.2f}")
print(f"Min: {np.min(image)}, Max: {np.max(image)}")
print("Histogram (counts per bin):", np.histogram(image, bins=5)[0])

# 5. Flip and rotate
print("\n5. Image Transformations:")
print("Horizontal flip:\n", np.fliplr(image))
print("Vertical flip:\n", np.flipud(image))
print("90 degree rotation:\n", np.rot90(image))

# 6. Create a gradient (for visualization)
print("\n6. Create a gradient image:")
gradient = np.arange(64).reshape(8, 8) * 4  # Creates a smooth gradient
print(gradient)

Original Image (8x8 pixel values):
 [[102 220 225  95 179  61 234 203]
 [ 92   3  98 243  14 149 245  46]
 [106 244  99 187  71 212 153 199]
 [188 174  65 153  20  44 203 152]
 [102 214 240  39 121  24  34 114]
 [210  65 239  39 214 244 151  25]
 [ 74 145 222  14 202  85 145 117]
 [ 87 184 189 221 116 237 109  85]]

--- Image Processing Operations ---

1. Brightness Adjustment (multiply by 1.5):
[[153 255 255 142 255  91 255 255]
 [138   4 147 255  21 223 255  69]
 [159 255 148 255 106 255 229 255]
 [255 255  97 229  30  66 255 228]
 [153 255 255  58 181  36  51 171]
 [255  97 255  58 255 255 226  37]
 [111 217 255  21 255 127 217 175]
 [130 255 255 255 174 255 163 127]]
Original mean: 137.28
Bright mean: 178.75

2. Contrast Enhancement (stretch to full range):
[[104 228 233  96 185  61 243 210]
 [ 93   0 100 252  11 153 255  45]
 [108 253 101 193  71 220 158 206]
 [194 180  65 158  17  43 210 157]
 [104 222 249  37 124  22  32 116]
 [218  65 248  37 222 253 155  23]
 [ 74 149 230  11 

## Summary: Key Concepts to Remember

### 1. **Array Creation**
- `np.array()` for custom arrays
- `np.zeros()`, `np.ones()`, `np.eye()` for special arrays
- `np.arange()`, `np.linspace()` for sequences

### 2. **Array Operations**
- All operations are **element-wise** by default
- Use `@` or `np.dot()` for **matrix multiplication**
- **Vectorization** is key for performance

### 3. **Indexing & Slicing**
- Basic: `arr[i, j]`
- Slicing: `arr[start:stop:step]`
- Boolean: `arr[arr > 5]`
- Fancy: `arr[[0,2,4]]`

### 4. **Reshaping**
- `reshape()` changes shape
- `flatten()` returns copy, `ravel()` returns view
- `vstack()`, `hstack()` for stacking

### 5. **Statistics**
- Use `axis=0` for columns, `axis=1` for rows
- `mean`, `median`, `std`, `var`, `percentile`
- `nanmean`, `nanstd` for data with missing values

### 6. **Performance**
- NumPy is **10-100x faster** than Python lists
- **Memory efficient**: 4-8x less memory
- Use vectorized operations, avoid loops

### 7. **Broadcasting**
- Operations on arrays of different shapes
- Dimensions must be compatible (equal or 1)
- Extremely useful for normalization, scaling

### 8. **Random Numbers**
- Set seed for reproducibility
- Many distributions: uniform, normal, binomial, etc.
- `choice()` for sampling, `permutation()` for shuffling

### 9. **Missing Data**
- NaN represents missing values
- Special functions: `isnan()`, `nanmean()`, `nan_to_num()`

### 10. **I/O**
- `.npy` for binary (fastest)
- `.npz` for multiple arrays
- `.csv` for interoperability

### When to Use NumPy:
✅ Large numerical datasets
✅ Matrix operations
✅ Statistical analysis
✅ Machine learning preprocessing
✅ Image processing
✅ Scientific simulations

### When to Use Python Lists:
✅ Small datasets
✅ Mixed data types
✅ Dynamic resizing needs
✅ Non-numerical data

---
**Additional Resources:**
- Official Documentation: https://numpy.org/doc/
- Quickstart Tutorial: https://numpy.org/doc/stable/user/quickstart.html
- NumPy for MATLAB users: https://numpy.org/doc/stable/user/numpy-for-matlab-users.html